### ISSUE TITLE
Error with binding false `bool` values and binding:"required"

### ISSUE THREAD

**Issue by oweidner** [martini-contrib/binding#42]
```
type ThisObj struct {
	ID         string       `json:"id"`
	Name       string       `json:"name" binding:"required"`
	Online     bool         `json:"online" binding:"required"`
}
```

In the above example, bind gives me a `RequiredError`when I POST the following JSON string:

```
{
    "name": "test",
    "online": false
}
```

However, when I set `online` to 'true' in the above JSON string, binding works fine. I assume this is a bug as a `false` value should still fulfill the `required` tag?

**Comment by mholt** [comment]
No, this is expected. The readme says,

> Note: Marking a field as "required" means that you do not allow the zero value for that type (i.e. if you want to allow 0 in an int field, do not make it required).

Because there is no way to differentiate between `false` and whether or not the data was submitted. This is because binding is a process independent of deserialization.

**Comment by oweidner** [comment]
Ah, never mind then. Thanks for clarifying!
